/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-high': '#ede8dc',
        'surface-variant': '#e7e2d6',
        'surface-bright': '#fef9ed',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dedace',
        'tertiary-fixed-dim': '#c8c6c6',
        'secondary': '#a23f00',
        'primary-fixed-dim': '#ffb4a2',
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#7c2e00',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'surface': '#fef9ed',
        'surface-container-low': '#f8f3e7',
        'on-secondary-fixed': '#351000',
        'inverse-surface': '#323029',
        'primary-fixed': '#ffdad2',
        'outline': '#8c716b',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#1b1c1c',
        'secondary-fixed-dim': '#ffb595',
        'on-primary-fixed-variant': '#891e02',
        'on-secondary-container': '#5c2000',
        'on-primary-container': '#ffd9d0',
        'surface-tint': '#aa3619',
        'tertiary-fixed': '#e4e2e1',
        'secondary-container': '#fc7127',
        'on-tertiary-container': '#e4e1e1',
        'primary-container': '#b23b1e',
        'surface-container': '#f2ede2',
        'tertiary': '#4c4c4c',
        'tertiary-container': '#656464',
        'inverse-on-surface': '#f5f0e4',
        'outline-variant': '#e0bfb8',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'background': '#fef9ed',
        'inverse-primary': '#ffb4a2',
        'on-background': '#1d1c15',
        'on-surface-variant': '#58413c',
        'on-surface': '#1d1c15',
        'primary': '#912307',
        'secondary-fixed': '#ffdbcd',
        'on-tertiary-fixed-variant': '#474747',
        'surface-container-highest': '#e7e2d6',
        'on-primary-fixed': '#3c0700',
        'on-primary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '48px',
        base: '8px',
        xs: '4px',
        'container-max': '1200px',
        md: '24px',
        sm: '12px',
        xl: '80px',
        gutter: '24px',
      },
      fontFamily: {
        'label-sm': ['Inter'],
        'body-lg': ['Inter'],
        'headline-md': ['Libre Caslon Text'],
        'headline-sm': ['Libre Caslon Text'],
        'display-lg-mobile': ['Libre Caslon Text'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'display-lg': ['Libre Caslon Text'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
